# Use root/example as user/password credentials
version: '3.1'

services:

  db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_DATABASE: "todo_db"
      MYSQL_ROOT_PASSWORD: passw0rd
    ports:
      - 127.0.0.1:3306:3306
    volumes:
      - ./database.sql:/docker-entrypoint-initdb.d/database.sql

  adminer:
    image: adminer
    restart: always
    environment:
      MYSQL_USER: user
      MYSQL_PASSWORD: passw0rd
      MYSQL_DATABASE: "todo_db"
    ports:
      - 127.0.0.1:8080:8080